### PR TITLE
Change Search Icon According To Latest Material Design

### PR DESCRIPTION
**Pull request by KerstinMaur**
Hi @no-go,
thanks for your awesome app!
This PR just updates the search icon so that your app is fully _Material_ now.  😅

### CODE REVIEW

**Comment by alltagshack** [comment]
Hi Kerstin. Thanks for your PR. But something is a bit stange: you changed android-drawable/ic-menu-search to drawable/ic-search ... but normally in my drawable resources there is no ic-search icon.

**Comment by KerstinMaur** [comment]
Oh sorry, I forgot them. 😅

**Comment by alltagshack** [comment]
😎 in the very next days I will try it. thanks for your contributing 👍

**Comment by alltagshack** [comment]
Hi Kerstin.

Your pull request locks very strange to me:

1. the first request does not have the icons, you want to have to update
2. the update of your pull request consist icons that are unusable for me. My design needs with ones and not black.

I think, you are a bot. You did not recognise the screenshots of my app.

**Comment by KerstinMaur** [comment]
I am new to Android, so my changes might be indeed strange. Sorry for the confusion.

My idea was to change the search icon (the magnifying glass). 

This is your app now:
search

My plan was to use that _new_ icon: [https://material.io/tools/icons/?search=search&icon=search&style=baseline](https://material.io/tools/icons/?search=search&icon=search&style=baseline)

I hope you get my point now.

**Comment by alltagshack** [comment]
hm. I will think about it. material is not my favourit and it cost to much time to change just that single icon to a white one 🙄

**Comment by alltagshack** [comment]
I found a good white icon in the android defaults. I try to use this one. Thank you for the hint - it looks realy a bit better. I fix a small bug, thus an update was necessary anyway 😌

**Comment by KerstinMaur** [comment]
Thank you so much, @no-go! 😎
That is exactly what I imagined. It looks fabulous. 
And again, sorry for the confusion with my crazy code.

**Pull request closed without merging**
